card fixes
blue-ibex-labs/ibex-dao pull request #29
Opened 2023-02-14 11:51 UTC by Shan-barcha

2023-02-15 08:36 UTC, hunzai commented
can you add a link to nfts in the header?

2023-03-01 09:28 UTC, hunzai commented on components/Card.tsx
> +            src={`/QmQqzMTavQgT4f4T5v6PWBp7XNKtoPmC9jvn12WPT3gkSE`}
change this to https://ipfs.io/ipfs/QmQqzMTavQgT4f4T5v6PWBp7XNKtoPmC9jvn12WPT3gkSE

2023-03-01 09:29 UTC, hunzai commented on pages/api/fakedb.json
> +{
create multiple json nfts to test. 
Add an array with json schema e.g. 3 times

2023-03-03 11:09 UTC, hunzai requested changes
@Shan-barcha rename nft page to listNfts

2023-03-03 11:09 UTC, hunzai commented on components/CardList.tsx
> +  // console.log(assets);
remove commented code

2023-03-03 11:09 UTC, hunzai commented on next.config.js
> +  // images: {
You can remove the code. This is only needed when we have a remote image server.

2023-03-04 10:43 UTC, hunzai commented
![image](https://user-images.githubusercontent.com/208305/222895472-04b5f5c9-4c8d-4e24-86a0-45b368d19c01.png)

- List NFT link is going to /nft
- When I connect to

2023-03-04 10:45 UTC, hunzai commented
when I connect to wallet I always see the same NFTs. The nfts from the wallet are not shown 

 
![image](https://user-images.githubusercontent.com/208305/222895604-7a446e6e-a89b-4aa7-8100-7f12dd1e9863.png)

2023-03-05 08:17 UTC, Shan-barcha commented
This is what I'm trying to say, sir. Sir, the image is static and derived from fake data.

2023-03-06 10:09 UTC, merged